all: compile link

compile:
	g++ -c main.cpp -I"D:\System_setup\sfml\SFML-2.6.1\include"
	g++ -c Food.cpp -I"D:\System_setup\sfml\SFML-2.6.1\include"
	g++ -c Snake.cpp -I"D:\System_setup\sfml\SFML-2.6.1\include"
link:
	g++ main.o Food.o Snake.o -o game -L"D:\System_setup\sfml\SFML-2.6.1\lib" -lsfml-graphics -lsfml-window -lsfml-system
clean:
	del main.exe main.o Food.o Snake.o

again: clean all
